### PR TITLE
Submission of my project for Lead to review

### PR DESCRIPTION
**Pull request by JackJJCodes**
Hey Aman,
Herewith attached is the project I was talking about. Please review it, and lemme know if it's alright :)

### CODE REVIEW

**Comment by JackJJCodes** [comment]
Hey Aman!
Sorry for the inconvenience earlier. I am just starting out with Git :)

Here, I hope now you are able to view my project.

**Comment by AM1CODES** [comment]
Hey @Jackson-hub it's always a good thing to attach some project screenshots as well so that it's easier for the maintainers to get the idea of the whole project. So just add in a few screenshots here in the conversation as well.

**Comment by JackJJCodes** [comment]
Right, apologies again. I am kinda new to all this so, bear with me :)

Here are the screen shots:

Screenshot from 2021-03-30 18-25-10

Screenshot from 2021-03-30 18-24-53

**Review by amansharma2910 — APPROVED** [review]
Great work! Merging the changes.
Thanks for your contribution!

**Pull request merged**
