### PR TITLE
Added the Book Recommender System

### PR DESCRIPTION
**Pull request by AM1CODES**
Added the files for the Book Recommender system. Files included - 
1)The Recommender System
2)Results of the Recommender System
3)The data used to make the system

### CODE REVIEW

**Comment by amansharma2910** [comment]
@AM1CODES can you please provide some images of your results? Also, I'd like to know the model architecture that you used for the recommender system?

**Comment by amansharma2910** [comment]
@AM1CODES can you please provide some images of your results? Also, I'd like to know the model architecture that you used for the recommender system?

**Comment by AM1CODES** [comment]
Result-1
Result-2
So, i used the Good-Reads book data set for making this recommender system. I have attached the results above for you to have a look at. So my approach was very simple. I started off with some Data Cleaning and EDA. After having an idea of what features to use, i created a new Data frame with the required features. I used the average ratings that each book had, the number of reviews a book had and the language it was written in. Fed these features to the KNN model in order to find the books that share the similar features. And that's how i reached to the results that i displayed above. That's all. I am open to any further questions that you might have regarding the System.

**Comment by amansharma2910** [comment]
Great. I am merging your commits. Just a quick note. The submission guidelines have been changed. Next time kindly create PRs only in the review branch. Thanks for your contribution!

**Comment by AM1CODES** [comment]
I will definitely follow the guidelines next time. Thankyou.

**Pull request merged**
